#!/usr/bin/env bash
#installingi load balancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5792-webs
    bind *:80
    mode http
    balance roundrobin
    server 5792-web-01 54.242.223.242 check
    server 5792-web-02 54.90.93.184 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart