#!/usr/bin/env bash
# comment
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 5681-web-01 54.242.223.242  check
        server 5681-web-02 54.90.93.184  check
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
